title: "Eduard Burcea | Cybersecurity Portfolio"
description: "Cybersecurity projects, writeups, and thoughts from an aspiring cybersecurity professional."
show_downloads: false
url: "https://cyegreen.github.io/"
theme: jekyll-theme-hacker

# Social Media Links
github_username: "cyegreen"
linkedin_username: "eduardburcea"
twitter_username: "cyegreen_"

# Google Analytics
google_analytics: ""

# Navigation Links
header_pages:
  - index.md
  - projects.md
  - writeups.md
  - coursework.md
  - about.md
